### ISSUE TITLE
Add fromKeptn label

### ISSUE THREAD

**Issue by ghost** [keptn-sandbox/jira-service#11]
Enhancement request: Add `fromKeptn` label to each ticket from this service.

Rationale: Provides the ability to show all keptn issues in a single filter.

Requested By: @robertjahn

**Comment by ghost** [comment]
I don't think this is necessary since #9, #10 and #12 now provide comprehensive label support. So it's now easy to filter by any `keptn_*` label (or any other label you choose to send in via JSON).

The service also has the option to create any type of issue (ie. not just `Task`s) by adjusting the value of the `secret`. Thus you could create an issue type dedicated to Keptn output. That's what I'd recommend in this case.

**Comment by robertjahn** [comment]
I agree, if keptn-project, keptn-service, keptn-stage labels are being added then we don't also need "fromKeptn"
