### ISSUE TITLE
Link to Parent Issue

### ISSUE THREAD

**Issue by ghost** [keptn-sandbox/jira-service#13]
Link issues if there is a parent issue.

Requested by: @robertjahn

If a JIRA ticket is created and an evaluation is requested _from_ that ticket, We should link the evaluation-done ticket to the parent (originating ticket).

For the purposes of this ticket we will standardise on the `key` of `jira_issue`. We will also assume that the parent is responsible for adding the `jira_issue` key to the labels value of the `start-evaluation` JSON.

eg.

```
"labels": {
  "jira_issue": "AB-123"
}
```

**Comment by robertjahn** [comment]
Do you think the service should expect the org as in these examples?  or do you want to assume to use the jira-base-url from the jira-details secret?

```
"labels": {
  "jira-issue": "AB-123",
  "jira-org": "https://dynatracedemos.atlassian.net"
}
```
or perhaps
```
"labels": {
  "jira-issue": "AB-123",
  "jira-org": "dynatracedemos
}
```
