### ISSUE TITLE
Add Bridge Hyperlink to Issue

### ISSUE THREAD

**Issue by ghost** [keptn-sandbox/jira-service#14]
Add the hyperlink to the Keptn's bridge for a direct link from the ticket.

Requested by: @robertjahn

**Comment by ghost** [comment]
Basic idea: Add this as a JIRA (remote) web link.

![image](https://user-images.githubusercontent.com/13639658/80367037-b421ab00-88cd-11ea-9a36-c5c5e68d52b3.png)

```
POST https://abc123.atlassian.net/rest/api/2/issue/PROJ-1234/remotelink
{
  "object": {
    "url": "https://example.com",
    "title": "Keptn's Bridge >>",
    "icon": {
      "url16x16": "https://dt-cdn.net/images/favicon-48x48-transparent-48-9b4df9c769.png"
    }
  }
}
```

**Comment by robertjahn** [comment]
For for Bridge Deep Link is

https://bridge.keptn.MYDOMAIN/project/KEPTN-PROJECT/KEPTN-SERVICE/KEPTN-CONTEXT-ID/KEPTN-CLOUD-EVENT-ID

For example:
https://bridge.keptn.MYDOMAIN/project/bitbucket-demo/simplenodeservice/16761053-ac68-4f09-8e76-96798f44b30c/c9fc2007-4d28-4697-b894-26d4cc2482a6

this is payload example for the URL above
{
  "contenttype": "application/json",
  "data": {
    "customFilters": [],
    "deployment": "",
    "deploymentstrategy": "",
    "end": "2020-04-13T18:15:45Z",
    "indicators": [
      "response_time_p95",
      "throughput",
      "error_rate",
      "response_time_p50",
      "response_time_p90",
      "rt_url_apiinvoke",
      "rt_test_invoke",
      "failurerate_test_invoke"
    ],
    "labels": {
      "bitbucket-build": "159",
      "jira-issue": "DD-13",
      "jira-org": "dynatracedemos",
      "source": "bitbucket"
    },
    **"project": "bitbucket-demo",
    "service": "simplenodeservice",**
    "sliProvider": "dynatrace",
    "stage": "staging",
    "start": "2020-04-13T18:14:38Z",
    "teststrategy": "manual"
  },
  **"id": "c9fc2007-4d28-4697-b894-26d4cc2482a6",**
  "source": "lighthouse-service",
  "specversion": "0.2",
  "time": "2020-04-22T14:15:01.455Z",
  "type": "sh.keptn.internal.event.get-sli",
  **"shkeptncontext": "16761053-ac68-4f09-8e76-96798f44b30c",**
  "icon": "collector",
  "label": "Start SLI retrieval"
}

**Comment by ghost** [comment]
Done in https://github.com/keptn-sandbox/jira-service/commit/d0dfc13991302e90ae950a039b32abefb2cc7bef
