### ISSUE TITLE
Update New JIRA Issue Description for Keptn Problem Open events

### ISSUE THREAD

**Issue by robertjahn** [keptn-sandbox/jira-service#15]
Here is the proposed template

JIRA ticket title = [PROBLEM] {ProblemTitle}
Description = 
 
{ImpactedEntity}
Problem detected at {startTime  <-- the cloud event has this UNIX time, so it needs to be human readable formatted }
project: {project}
service: {service}
stage: {stage}
 
Dynatrace problem ID: { ProblemID}
Dynatrace impact level: {impactLevel}
Dynatrace severity evel: {severityLevel}
 
Dynatrace: {Problem URL}
Keptn Bridge: {Bridge URL}

Here is an example

[PROBLEM] frontend AVAILABILITY_EVENT 2020-04-23T15:24:07.069Z
 
Description:
 
frontend AVAILABILITY_EVENT 2020-04-23T15:24:07.069Z on Web request service k8-bitbucket-demo-production-simplenodeservice-
Problem detected at: 2020-04-23T15:28:00.435Z
 
project: bitbucket-demo
service: simplenodeservice
stage: production
 
Dynatrace problem ID: { ProblemID}
Dynatrace impact Level: SERVICE
Dynatrace severity Level: AVAILABILITY
 
Dynatrace: https://gan16820.live.dynatrace.com/#problems/problemdetails;pid=-3014741983814050006_1587767160000V2;gf=all
Keptn Bridge: https://bridge.keptn.jahn-keptn-quality-gate.alliances.dynatracelabs.com/project/bitbucket-demo/simplenodeservice/37393738-3231-4134-b834-353233363939

**Comment by ghost** [comment]
Does this help?

![image](https://user-images.githubusercontent.com/13639658/80561322-691bab00-8a27-11ea-9790-0e79c735aafb.png)
