### ISSUE TITLE
Make Result More Visual

### ISSUE THREAD

**Issue by ghost** [keptn-sandbox/jira-service#20]
How hard is it to add color/bold? example:
![image](https://user-images.githubusercontent.com/24907089/80605198-c05a5500-8a00-11ea-8dcf-2f069fb86331.png)

_Originally posted by @robertjahn in https://github.com/keptn-sandbox/jira-service/issues/16#issuecomment-621244900_

**Comment by ghost** [comment]
@robertjahn Given the prevalance of red / green colour blindness, I propose this instead:

![image](https://user-images.githubusercontent.com/13639658/80655131-48079880-8ac1-11ea-8a1f-946aabe5ccf2.png)

**Comment by robertjahn** [comment]
works for me!
