### ISSUE TITLE
Send Event to Dynatrace

### ISSUE THREAD

**Issue by ghost** [keptn-sandbox/jira-service#6]
This enhancement would see the jira-service sending a notification back to Dynatrace whenever a JIRA ticket is created (or a creation attempt is made).

This feature should have a corresponding enable / disable flag.

**Thoughts**
1. Is this the best place for this logic? Should it not live elsewhere?
2. Can this notification be made more generic for any tool (not just Dynatrace)?

**Comment by ghost** [comment]
@christian-kreuzberger-dtx interested on your thoughts. A generic "here's a payload, send an event" type facility would be great - perhaps this logic lives in the `dynatrace-service` or an extension of the `notification-service`?

**Comment by christian-kreuzberger-dtx** [comment]
That's definately something for dynatrace-service. Feel free to post a Feature Request for this service.
