### ISSUE TITLE
Enhancement: Create labels for core keptn tags

### ISSUE THREAD

**Issue by ghost** [keptn-sandbox/jira-service#9]
Create labels for the core keptn tags:
`keptn_project:sockshop`, `keptn_service:carts` and `keptn_stage:dev`.

**Comment by ghost** [comment]
Completed in https://github.com/keptn-sandbox/jira-service/pull/4/commits/033cab6f2164e354a8594640bf7ba8dc65e3d79d

**Comment by robertjahn** [comment]
I am seeing the labels that are in the cloud event.  

![image](https://user-images.githubusercontent.com/24907089/80405496-b1549500-8890-11ea-9488-8f8c6a2c78bb.png)

I suggest having just the keptn-project, keptn-service, keptn-stage, keptn-result.

**Comment by robertjahn** [comment]
I am seeing the three labels OK in JIRA for he PROBLEM.OPEN event.

![image](https://user-images.githubusercontent.com/24907089/80406280-d09ff200-8891-11ea-9804-079ea303267d.png)

But for the EVALUATION, in JIRA I am seeing these plus the labels from the cloud event.  I think we want just the keptn-project, keptn-service, keptn-stage.  But if, if you need to into the code adding a keptn-result label would be nice to have too.

![image](https://user-images.githubusercontent.com/24907089/80405496-b1549500-8890-11ea-9488-8f8c6a2c78bb.png)
